SELECT * FROM customer limit 20
--Q1. What is the total revenue generated by male vs. female customers?


select gender,sum(purchase_amount)
from customer
group by gender;
--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount
from customer where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)
--Q3. What are the top 5 products with the highest average review rating?

select item_purchased, Round(AVG(review_rating)::numeric,2) as average_rating
from customer
group by item_purchased
order by average_rating desc
limit 5
--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type,Round(AVG(purchase_amount)::numeric,2)
from customer
where shipping_type in ('Express','Standard')
group by shipping_type
--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status,
count(customer_id) as total_customer,
Round(AVG(purchase_amount)::numeric,2) as average_spending,
sum(purchase_amount) as total_revenue
from customer
group by subscription_status
--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select
item_purchased,
Round(100 *SUM(case when discount_applied = 'Yes' then 1 else 0 end )/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases,
--and show the count of each segment.

with cte_customer_type as (
select customer_id,previous_purchases,
	case
	    when previous_purchases = 1 then 'New'
		when previous_purchases between 2 and 10 then 'Returning'
		else 'loyal'
	end as customer_segment 
from customer )

select customer_segment,count(*) as total_customer
from cte_customer_type
group by customer_segment

--Q8. What are the top 3 most purchased products within each category?

with cte_item_counts as (
select category,item_purchased,
count(customer_id) as total_customer,
ROW_NUMBER() over (partition by category order by count(customer_id) desc ) as item_rank
from customer
group by category,item_purchased
)

select category,item_purchased,item_rank,total_customer
from cte_item_counts
where item_rank <= 3;
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as total_customer
from customer
where previous_purchases > 5
group by subscription_status

--Q10. What is the revenue contribution of each age group

select 
age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc
